# Generated by Django 2.1.15 on 2021-03-04 18:36

import core.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=core.models.painting_image_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='PaintingDescriptors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptors', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=32), size=None)),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Painting')),
            ],
        ),
    ]
