version: "3"

services:
  app:
    build:
      context: . # current directory
    ports:
      - "8000:8000" # host to image map
    volumes:
      - ./app:/app # automatically update changes made on local machine so that you dont have to restart docker
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment: 
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=pass
    depends_on: 
      - db
    


  db:
    image: postgres:10-alpine
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
